var data = 
{ "meta": { "title" : "Notesoble",
	    "author": "by The Novice Oof",
	    "copyright":"All code is MIT Licensed",
	    "version":"2011/2/5",
	    "last-height":2},
  "docs":
  ["Notesoble.com is your one stop resource for next generation documentation chock-full of interaction and an emphasis on facilitating comprehension",
   "Click the arrows to the left to expand and fold up content",
   [{"text":"News","type":"h1"},
    ["We're in pre-alpha, so there ain't no news. We're working on this, though"]],
   [{"text":"Quickstart with Notesoble","type":"h1"},
    ["So far, Notesoble is just a javascript compiler and a pile of JSON.",
     "There is no quickstart, mostly because if you want to use Notesoble, you have to come and hack on code with us.",
     "However, I guess I should show you guys fun things we can do so far with Notesoble:",
{"text":"function stuff(){\n\talert('hello');\n}","type":"code"},
{"text":"\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}","type":"math"},
     "And that's all for now!"]],
   [{"text":"About Notesoble","type":"h1"},
    ["Notesoble is a protest against the failure of electronic textbooks to leverage the base computing power available to them",
     "Notesoble is an attempt to increase comprehension with visual tropes",
     "Notesoble is a way to quickly make documents that make sense, and make it easy to edit and revise in ways that make sense"]],
   [{"text":"Download Notesoble","type":"h1"},
    ["At the moment, all you can do is grab the base code from github",
     "Eventually, we plan on providing the server and client code in nice, documented packages under open source licenses"]],
   ]
};